export const categoryList = [
    {
      id: 1,
      value: 'men',
      label: '👨 MEN',
    },
    {
      id: 2,
      value: 'women',
      label: '👩 WOMEN',
    },
  ];
  
  export const ratingList = [
    {
      id: 1,
      value: '1',
      label: '1🌟',
    },
    {
      id: 2,
      value: '2',
      label: '2🌟',
    },
    {
      id: 3,
      value: '3',
      label: '3🌟',
    },
    {
      id: 4,
      value: '4',
      label: '4🌟',
    },
    {
      id: 5,
      value: '5',
      label: '5🌟',
    },
  ];
  
  export const dataList = [
    {
      id: 1,
      title: 'Hawaiian shirt',
      deliveryFee: 3.44,
      category: 'MEN',
      brand: 'H&M',
      rating: 5,
      price: 2500,
      coverSrc: '/images/men/h&m_1.jpg',
    },
    {
      id: 2,
      title: 'White Top',
      deliveryFee: 4.94,
      category: 'WOMEN',
      brand: 'H&M',
      rating: 4,
      price: 1000,
      coverSrc: '/images/women/h&m_1.jpg',
    },
    {
      id: 3,
      title: 'NF T-shirt',
      deliveryFee: 4.94,
      category: 'WOMEN',
      brand: 'North Face',
      rating: 3,
      price: 2000,
      coverSrc: '/images/women/northface_1.jpg',
    },
    {
      id: 4,
      title: 'Pink T-shirt',
      deliveryFee: 2.14,
      category: 'MEN',
      brand: 'H&M',
      rating: 1,
      price: 1800,
      coverSrc: '/images/men/h&m_2.jpg',
    },
    {
      id: 5,
      title: 'NF Black Jacket',
      deliveryFee: 6.79,
      categorY: 'place',
      brand: 'North Face',
      rating: 5,
      price: 2000,
      coverSrc: '/images/men/northface_1.jpg',
    },
    {
      id: 6,
      title: 'Hawaiian White',
      deliveryFee: 2.87,
      category: 'MEN',
      brand: 'Zara',
      rating: 5,
      price: 3500,
      coverSrc: '/images/men/zara_2.jpg',
    },
    {
      id: 7,
      title: 'Black Top',
      deliveryFee: 8.5,
      category: 'WOMEN',
      brand: 'Zara',
      rating: 4,
      price: 2200,
      coverSrc: '/images/women/zara_2.jpg',
    },
    {
      id: 8,
      title: 'Green Top',
      deliveryFee: 1.8,
      category: 'WOMEN',
      brand: 'H&M',
      rating: 1,
      price: 1900,
      coverSrc: '/images/women/h&m_2.jpg',
    },
    {
      id: 9,
      title: 'Denim Skirt',
      deliveryFee: 3.33,
      category: 'WOMEN',
      brand: 'Zara',
      rating: 4,
      price: 2750,
      coverSrc: '/images/women/zara_1.jpg',
    },
    {
      id: 10,
      title: 'NF Aqua Jacket',
      deliveryFee: 1.9,
      category: 'MEN',
      cuisine: 'american',
      rating: 2,
      price: 4350,
      coverSrc: '/images/men/northface_2.jpg',
    },
    {
      id: 11,
      title: 'Bandana Shirt',
      deliveryFee: 4.1,
      category: 'MEN',
      brand: 'Zara',
      rating: 3,
      price: 3300,
      coverSrc: '/images/men/zara_1.jpg',
    },
    {
      id: 12,
      title: 'Pink Jacket',
      deliveryFee: 1.5,
      category: 'WOMEN',
      brand: 'North Face',
      rating: 2,
      price: 4100,
      coverSrc: '/images/women/northface_2.jpg',
    },
];